services:
  fitwsarah:
    build: .
    hostname: fitwsarah
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  reactapp:
    build:
      context: ./fitwsarah_frontend
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    depends_on:
      - fitwsarah