services:
  fitwsarah:
    build: .
    hostname: fitwsarah
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_ID2=${AUTH0_CLIENT_ID2}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
    depends_on:
      mysql1:
        condition: service_healthy

  mysql1:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=fitwsarah-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/mysql1
      - ./data/init.d:/docker-entrypoint-initdb.d

    platform: linux/amd64


    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  reactapp:
    build:
      context: ./fitwsarah_frontend
      dockerfile: Dockerfile.react
      args:
        - REACT_APP_AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
        - REACT_APP_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
        - REACT_APP_BASE_URL=${BASE_URL}
        - REACT_APP_DEVELOPMENT_URL=${DEVELOPMENT_URL}
    ports:
      - "3000:80"
    depends_on:
      - fitwsarah