services:
  fitwsarah:
    build: .
    hostname: fitwsarah
    ports:
      - "8080:8080"
    env_file:
      - .env

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  reactapp:
    build:
      context: ./fitwsarah_frontend
      dockerfile: Dockerfile.react
      args:
        - REACT_APP_AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
        - REACT_APP_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
        - REACT_APP_BASE_URL=${BASE_URL}
        - REACT_APP_DEVELOPMENT_URL=${DEVELOPMENT_URL}
    ports:
      - "3000:80"
    depends_on:
      - fitwsarah