# Default Spring Profile
server:
  error:
    include-message: always
  port: ${PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://avnadmin:AVNS__XXPepyHbcL_QFVOk2o@fitwsarah-fitwsarahdb.a.aivencloud.com:20883/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS__XXPepyHbcL_QFVOk2o
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none

logging:
  level:
    root: INFO
    com.fitwsarah: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

okta:
  oauth2:
    issuer: https://dev-twa7h1nv0usycyum.us.auth0.com/
    audience: https://dev-twa7h1nv0usycyum.us.auth0.com/api/v2/

# for docker
---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-twa7h1nv0usycyum.us.auth0.com/
