# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.fitwsarah: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

okta:
  oauth2:
    issuer: https://dev-twa7h1nv0usycyum.us.auth0.com/
    audience: https://dev-twa7h1nv0usycyum.us.auth0.com/api/v2/

---
# for docker

spring:
  datasource:
    url: jdbc:mysql://ufoi51cd4vdjv72c:PGPr4sCr6c6pI6qJpjco@brrxxmh3hcgspalv0jkt-mysql.services.clever-cloud.com:3306/brrxxmh3hcgspalv0jkt
    username: ufoi51cd4vdjv72c
    password: PGPr4sCr6c6pI6qJpjco
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always

  main:
    allow-bean-definition-overriding: true

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000