name: CI/CD Pipeline NPM

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.ref == 'refs/heads/master'
    permissions:
      contents: write
      pull-requests: write
      checks: write
    environment:
      name: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: npm install, build, and test
        working-directory: fitwsarah_frontend
        run: |
          npm ci
          
          npm run build --if-present
          npm start & npx wait-on http://127.0.0.1:3000
        env:
          CI: false

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONTEND }}
        run: |
          curl "$deploy_url"
